### ISSUE TITLE
Links keep getting selected even when I select a different link

### ISSUE THREAD

**Issue by kaviththiranga** [wso2/ballerina-vscode#300]
**Description:**
<img width="1235" alt="image" src="https://user-images.githubusercontent.com/1505855/201908739-a847345b-e5b4-4e40-97d3-8c855f979055.png">

When I click on a different link, the previously selected link should get unselected.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by madushajg** [comment]
This is no longer reproducible, hence closing
