### ISSUE TITLE
Data mapper import a json fails when there is two objects with the same name in the json input.

### ISSUE THREAD

**Issue by anupama-pathirage** [wso2/ballerina-vscode#405]
**Description:**
$subject when using a file with the following json content.

Click `Design` -> `Import a Json` -> upload the json file -> and select `Make Separate Record Definitions`

```json
{
	"id": "0001",
	"name": "Cake",
	"score": 0.55,
	"status": {
		"id": "1001",
		"type": "Regular"
	},
	"position": {
		"status": {
			"sid": 4,
			"xpos": "DF"
		},
		"location": "center"
	}
}
```

**Comment by madushajg** [comment]
@anupama-pathirage Were you able to create a record def if all the fields are unique?
ie:
```json
{
	"id": "0001",
	"name": "Cake",
	"score": 0.55,
	"status": {
		"kind": "D"
	}
}
```

**Comment by madushajg** [comment]
> > @anupama-pathirage Were you able to create a record def if all the fields are unique? ie:
> > ```json
> > {
> > 	"id": "0001",
> > 	"name": "Cake",
> > 	"score": 0.55,
> > 	"status": {
> > 		"kind": "D"
> > 	}
> > }
> > ```
> 
> Yes, If all the fields are unique the records are creating without any issue. i.e. if you rename one of the `status` field to `status1` it works well.

Thanks! I also reproduced this in Ballerina `2201.3.1`. 
However the separate record defs are not generated in  `2201.3.2` even the fields are unique. Created another issue to track  that (https://github.com/wso2/ballerina-plugin-vscode/issues/408)
Will work on fixing those soon.

**Comment by madushajg** [comment]
The issue still persists if there are multiple arrays with the same name in the json. Hence re-opening.

**Comment by madushajg** [comment]
Tested with Ballerina `2201.8.0` and the issue has been fixed. Hence closing the issue.
