### ISSUE TITLE
Service editing is not working in Windows

### ISSUE THREAD

**Issue by anupama-pathirage** [wso2/ballerina-vscode#534]
**Description:**

$subject in Windows. I am trying to edit a simple resource and the diagram editor is getting freezed when doing that.

**The sample code:**

```ballerina
import ballerina/http;

listener http:Listener httpListener = new (8080);

service / on httpListener {
    resource function get greeting() returns string { 
        return "Hello, World!"; 
    }

    resource function get greeting/[string name]() returns string { 
        return "Hello " + name; 
    }
}
```

**Windows version**

Windows 10 Enterprise

**Ballerina Version**

Plugin version V4.5.3

![image](https://github.com/wso2/ballerina-vscode/assets/16300038/16db59dd-b10d-41f4-9ee6-f914124500a9)

See the recording below

https://github.com/wso2/ballerina-vscode/assets/16300038/d16ea446-94e0-4d13-a5a5-7299409b640d

**Comment by kaviththiranga** [comment]
@axewilledge FYI. I will try to reproduce.

**Comment by kaviththiranga** [comment]
@anupama-pathirage Can you please confirm the VSCode version you are using?

I tried to reproduce this with VSCode 1.83.1, on windows 10 pro. But could not reproduce it. 


https://github.com/wso2/ballerina-vscode/assets/1505855/05bd2996-eed1-412b-8a37-5648138d78e8

**Comment by axewilledge** [comment]
I tried with windows 11 and VSCode 1.83.1 and there is a delay in showing the form. Didn't get a freeze but the delay it self seemed like a freeze. Will try to debug the delay.
