### ISSUE TITLE
Increase the character length for the function names in Low-code view

### ISSUE THREAD

**Issue by dilanSachi** [wso2/ballerina-vscode#567]
**Description:**
![image](https://github.com/wso2/ballerina-vscode/assets/35135122/b89a3b5c-95eb-4309-a9fc-9345a6f53f27)

Here the function name `check getJwtClaims` is stripped and shown. Instead its better if we can show `getJwtClaims`

**Comment by kanushka** [comment]
This issue has been fixed with this PR 
https://github.com/wso2-enterprise/vscode-extensions/pull/3166
